export const data = JSON.parse("{\"key\":\"v-6c8817e6\",\"path\":\"/%E5%89%8D%E7%AB%AF/HTMLCSS/01.html\",\"title\":\"常用布局\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"常用布局\",\"cover\":\"/assets/images/cover1.jpg\",\"icon\":\"file\",\"order\":1,\"author\":\"silengzi\",\"date\":\"2024-07-10T00:00:00.000Z\",\"category\":[\"前端\"],\"tag\":[\"HTML\",\"CSS\"],\"sticky\":true,\"star\":true,\"footer\":\"这是测试显示的页脚\",\"copyright\":\"无版权\",\"description\":\"Flex布局 flex容器属性： flex-direction（子元素排列顺序） ``` flex-direction:属性规定灵活项目的排列方向（主轴方向）: row:默认值,灵活的项目将水平显示。 row-reverse:与row相同，但是以相反的顺序。 column:灵活的项目将垂直显示。 column-reverse:与column相同，但是以...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/cube-interview/%E5%89%8D%E7%AB%AF/HTMLCSS/01.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"面试宝典\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"常用布局\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Flex布局 flex容器属性： flex-direction（子元素排列顺序） ``` flex-direction:属性规定灵活项目的排列方向（主轴方向）: row:默认值,灵活的项目将水平显示。 row-reverse:与row相同，但是以相反的顺序。 column:灵活的项目将垂直显示。 column-reverse:与column相同，但是以...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/cube-interview/assets/images/cover1.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"常用布局\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"silengzi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"HTML\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"CSS\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-07-10T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"常用布局\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/cube-interview/assets/images/cover1.jpg\\\"],\\\"datePublished\\\":\\\"2024-07-10T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"silengzi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Flex布局\",\"slug\":\"flex布局\",\"link\":\"#flex布局\",\"children\":[{\"level\":3,\"title\":\"flex容器属性：\",\"slug\":\"flex容器属性\",\"link\":\"#flex容器属性\",\"children\":[]},{\"level\":3,\"title\":\"flex子元素属性：\",\"slug\":\"flex子元素属性\",\"link\":\"#flex子元素属性\",\"children\":[]}]},{\"level\":2,\"title\":\"Grid布局\",\"slug\":\"grid布局\",\"link\":\"#grid布局\",\"children\":[]}],\"readingTime\":{\"minutes\":6.67,\"words\":2001},\"filePathRelative\":\"前端/HTMLCSS/01.md\",\"localizedDate\":\"2024年7月10日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
