export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"首页","i":"home"},["/README.md"]],
  ["v-23316518","/frontend/01.html",{"y":"a","t":"什么是前端","i":"file","O":1},[":md"]],
  ["v-f5afdb16","/frontend/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":4},[":md"]],
  ["v-4bb22918","/frontend/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-42e2682a","/frontend/layout.html",{"y":"a","t":"布局","i":"object-group","O":2},[":md"]],
  ["v-8583e374","/frontend/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":4},[":md"]],
  ["v-3b660aa6","/frontend/page.html",{"y":"a","t":"页面配置","i":"file","O":3},[":md"]],
  ["v-06198984","/frontend/",{"y":"a","t":"前端","i":"laptop-code"},["/frontend/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
