export const data = JSON.parse("{\"key\":\"v-1801dbb8\",\"path\":\"/frontend/HTMLCSS/test/01%20copy.html\",\"title\":\"HTML+CSS\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"HTML+CSS\",\"cover\":\"/assets/images/cover1.jpg\",\"icon\":\"file\",\"order\":1,\"author\":\"silengzi\",\"date\":\"2024-07-09T00:00:00.000Z\",\"category\":[\"基础知识点\"],\"tag\":[\"HTML\",\"CSS\"],\"sticky\":true,\"star\":true,\"footer\":\"这是测试显示的页脚\",\"copyright\":\"无版权\",\"description\":\"HTML和CSS的基础知识，它们是构建Web页面的基础。HTML用于定义页面的结构，CSS用于定义页面的样式和布局。HTML和CSS是前端开发中不可缺少的技能，它们是构建Web页面的基础。 Flex布局 flex容器属性： flex-direction（子元素排列顺序） ``` flex-direction:属性规定灵活项目的排列方向（主轴方向）: r...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/cube-interview/frontend/HTMLCSS/test/01%20copy.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"面试宝典\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"HTML+CSS\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"HTML和CSS的基础知识，它们是构建Web页面的基础。HTML用于定义页面的结构，CSS用于定义页面的样式和布局。HTML和CSS是前端开发中不可缺少的技能，它们是构建Web页面的基础。 Flex布局 flex容器属性： flex-direction（子元素排列顺序） ``` flex-direction:属性规定灵活项目的排列方向（主轴方向）: r...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/cube-interview/assets/images/cover1.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"HTML+CSS\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"silengzi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"HTML\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"CSS\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-07-09T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"HTML+CSS\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/cube-interview/assets/images/cover1.jpg\\\"],\\\"datePublished\\\":\\\"2024-07-09T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"silengzi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Flex布局\",\"slug\":\"flex布局\",\"link\":\"#flex布局\",\"children\":[{\"level\":3,\"title\":\"flex容器属性：\",\"slug\":\"flex容器属性\",\"link\":\"#flex容器属性\",\"children\":[]}]}],\"readingTime\":{\"minutes\":69.26,\"words\":20779},\"filePathRelative\":\"frontend/HTMLCSS/test/01 copy.md\",\"localizedDate\":\"2024年7月9日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
